# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
