# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0002_auto_20170616_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='userId',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
